-- [ -> {
-- : -> =
-- "ID" -> ID
-- %20 -> space
-- %27 -> '	
-- Expac names (remove - raid)
-- remove \t\r\n
-- Rep -> Rep


	Attune_Data.attunes = 
	{
	--
	{ID="0",NAME="Debug",EXPAC="Testing", GROUP='MISC', FACTION="Both",ICON="Interface\\Icons\\inv_misc_questionmark", "This is a simple debug attune, not to be used by non-developers"},
	--
	{ID="1",NAME="Test multiple items",EXPAC="Testing", GROUP='MISC', FACTION="Both",ICON="Interface\\Icons\\inv_fabric_linen_01", "This is a simple debug attune, not to be used by non-developers"},
	--vanilla
	{ID="2",NAME=Lang["Molten Core"], ATTLOC=Lang["Molten Core"], TYPE="Raid", EXPAC=Lang["World of Warcraft"], GROUP=Lang['RAIDS'], FACTION="Both",ICON="Interface\\Icons\\inv_hammer_unique_sulfuras", DESC=Lang["MC_Desc"], GROUPSIZE=40, SHOWRAIDPLANNER=1},
	{ID="3",NAME=Lang["Onyxia's Lair"], ATTLOC=Lang["Onyxia's Lair"], TYPE="Raid", EXPAC=Lang["World of Warcraft"], GROUP=Lang['RAIDS'], FACTION="Horde",ICON="Interface\\Icons\\inv_misc_head_dragon_01", DESC=Lang["Ony_Desc"], GROUPSIZE=40, SHOWRAIDPLANNER=1},
	{ID="4",NAME=Lang["Onyxia's Lair"], ATTLOC=Lang["Onyxia's Lair"], TYPE="Raid", EXPAC=Lang["World of Warcraft"], GROUP=Lang['RAIDS'], FACTION="Alliance",ICON="Interface\\Icons\\inv_misc_head_dragon_01", DESC=Lang["Ony_Desc"], GROUPSIZE=40, SHOWRAIDPLANNER=1},
	--{ID="5",NAME=Lang["Blackwing Lair"], ATTLOC=Lang["Blackwing Lair"], TYPE="Raid", EXPAC=Lang["World of Warcraft"], GROUP=Lang['RAIDS'], FACTION="Both",ICON="Interface\\Icons\\inv_misc_head_dragon_black", DESC=Lang["BWL_Desc"], GROUPSIZE=40, SHOWRAIDPLANNER=1},
	--{ID="6",NAME=Lang["Naxxramas"], ATTLOC=Lang["Naxxramas"], TYPE="Raid", EXPAC=Lang["World of Warcraft"], GROUP=Lang['RAIDS'], FACTION="Both",ICON="Interface\\Icons\\inv_trinket_naxxramas06", DESC=Lang["All_Desc"], GROUPSIZE=40, SHOWRAIDPLANNER=1},
	{ID="8",NAME=Lang["Aqual Quintessence"], ATTLOC="", TYPE="",EXPAC=Lang["World of Warcraft"], GROUP=Lang['MISC'], FACTION="Both",ICON="Interface\\Icons\\inv_potion_76", DESC=Lang["MC2_Desc"]},
	--{ID="10",NAME=Lang["Scepter of the Shifting Sands"], TYPE="",ATTLOC="", EXPAC=Lang["World of Warcraft"], GROUP=Lang['MISC'], FACTION="Both",ICON="Interface\\Icons\\inv_hammer_25", DESC=Lang["AQ_Desc"]},
	{ID="12",NAME=Lang["Blackrock Depths"], ATTLOC="", TYPE="", EXPAC=Lang["World of Warcraft"], GROUP=Lang['KEYS'], FACTION="Both",ICON="Interface\\Icons\\inv_misc_key_08", DESC=Lang["OnlyOne_Desc"]},
	{ID="14",NAME=Lang["Scholomance"], ATTLOC="" --[[ NO ATTUNEMENT, JUST KEY]], TYPE="", EXPAC=Lang["World of Warcraft"], GROUP=Lang['KEYS'], FACTION="Horde",ICON="Interface\\Icons\\inv_misc_key_11", DESC=Lang["OnlyOne_Desc"]},
	{ID="15",NAME=Lang["Scholomance"], ATTLOC="", TYPE="", EXPAC=Lang["World of Warcraft"], GROUP=Lang['KEYS'], FACTION="Alliance",ICON="Interface\\Icons\\inv_misc_key_11", DESC=Lang["OnlyOne_Desc"]},



	Attune_Data.steps = 
	{
	{ID_ATTUNE="2",ID="20",TYPE="Level",STEP=Lang["Reach level"].." 55",LOCATION="",ID_WOWHEAD="55",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="1"},
	{ID_ATTUNE="2",ID="30",TYPE="Pick Up",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="26303",ICON="Interface\\Icons\\spell_fire_selfdestruct",FOLLOWS="20",STAGE="2"},
	{ID_ATTUNE="2",ID="40",TYPE="Turn In",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26303",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="30",STAGE="3"},
	{ID_ATTUNE="2",ID="50",TYPE="Pick Up",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26304",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="40",STAGE="4"},
	{ID_ATTUNE="2",ID="60",TYPE="Item",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="4625",ICON="Interface\\Icons\\inv_misc_herb_19",FOLLOWS="50",STAGE="5"},
	{ID_ATTUNE="2",ID="70",TYPE="Item",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="3819",ICON="Interface\\Icons\\inv_misc_flower_03",FOLLOWS="50",STAGE="5"},
	{ID_ATTUNE="2",ID="80",TYPE="Item",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="7068",ICON="Interface\\Icons\\spell_fire_fire",FOLLOWS="50",STAGE="5"},
	{ID_ATTUNE="2",ID="90",TYPE="Item",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="7070",ICON="Interface\\Icons\\inv_potion_03",FOLLOWS="50",STAGE="5"},
	{ID_ATTUNE="2",ID="100",TYPE="Turn In",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26304",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="60&70&80&90",STAGE="6"},
	{ID_ATTUNE="2",ID="110",TYPE="Pick Up",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26305",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="100",STAGE="7"},
	{ID_ATTUNE="2",ID="120",TYPE="Item",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="61960",ICON="Interface\\Icons\\inv_gizmo_khoriumpowercore",FOLLOWS="110",STAGE="8"},
	{ID_ATTUNE="2",ID="130",TYPE="Item",STEP="",LOCATION=Lang["Burning Steppes"],ID_WOWHEAD="61959",ICON="Interface\\Icons\\inv_misc_orb_05",FOLLOWS="110",STAGE="8"},
	{ID_ATTUNE="2",ID="140",TYPE="Turn In",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26305",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="120&130",STAGE="9"},
	{ID_ATTUNE="2",ID="150",TYPE="Pick Up",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26306",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="140",STAGE="10"},
	{ID_ATTUNE="2",ID="160",TYPE="Item",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="18412",ICON="Interface\\Icons\\inv_misc_gem_opal_01",FOLLOWS="150",STAGE="11"},
	{ID_ATTUNE="2",ID="170",TYPE="Item",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="61961",ICON="Interface\\Icons\\inv_potion_14",FOLLOWS="150",STAGE="11"},
	{ID_ATTUNE="2",ID="180",TYPE="Turn In",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26306",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="170",STAGE="12"},
	{ID_ATTUNE="2",ID="190",TYPE="Pick Up",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26307",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="180",STAGE="13"},
	{ID_ATTUNE="2",ID="200",TYPE="Interact",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="13278",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="190",STAGE="14"},
	{ID_ATTUNE="2",ID="210",TYPE="Turn In",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="26307",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="200",STAGE="15"},
	{ID_ATTUNE="2",ID="220",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_hammer_unique_sulfuras",FOLLOWS="210",STAGE="16"},

	{ID_ATTUNE="3",ID="10",TYPE="Level",STEP=Lang["Reach level"].." 55",LOCATION="",ID_WOWHEAD="55",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="10"},
	{ID_ATTUNE="3",ID="20",TYPE="Pick Up",STEP="",LOCATION=Lang["Badlands"],ID_WOWHEAD="4903",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="10",STAGE="50"},
	{ID_ATTUNE="3",ID="30",TYPE="Kill",STEP="",LOCATION=Lang["Lower Blackrock Spire"],ID_WOWHEAD="9196",ICON="Interface\\Icons\\inv_misc_head_centaur_01",FOLLOWS="20",STAGE="60"},
	{ID_ATTUNE="3",ID="40",TYPE="Kill",STEP="",LOCATION=Lang["Lower Blackrock Spire"],ID_WOWHEAD="9237",ICON="Interface\\Icons\\inv_misc_head_troll_01",FOLLOWS="20",STAGE="60"},
	{ID_ATTUNE="3",ID="50",TYPE="Kill",STEP="",LOCATION=Lang["Lower Blackrock Spire"],ID_WOWHEAD="9568",ICON="Interface\\Icons\\inv_misc_head_dragon_black",FOLLOWS="20",STAGE="60"},
	{ID_ATTUNE="3",ID="60",TYPE="Item",STEP="",LOCATION=Lang["Lower Blackrock Spire"],ID_WOWHEAD="12562",ICON="Interface\\Icons\\inv_scroll_02",FOLLOWS="20",STAGE="60"},
	{ID_ATTUNE="3",ID="65",TYPE="Turn In",STEP="",LOCATION=Lang["Badlands"],ID_WOWHEAD="4903",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60&30&40&50",STAGE="70"},
	{ID_ATTUNE="3",ID="70",TYPE="Quest",STEP="",LOCATION=Lang["Orgrimmar"],ID_WOWHEAD="4941",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="65",STAGE="80"},
	{ID_ATTUNE="3",ID="80",TYPE="Pick Up",STEP="",LOCATION=Lang["Orgrimmar"],ID_WOWHEAD="4974",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="70",STAGE="90"},
	{ID_ATTUNE="3",ID="90",TYPE="Kill",STEP="",LOCATION=Lang["Upper Blackrock Spire"],ID_WOWHEAD="10429",ICON="Interface\\Icons\\inv_misc_head_orc_01",FOLLOWS="80",STAGE="100"},
	{ID_ATTUNE="3",ID="95",TYPE="Turn In",STEP="",LOCATION=Lang["Orgrimmar"],ID_WOWHEAD="4974",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="90",STAGE="105"},
	{ID_ATTUNE="3",ID="100",TYPE="Quest",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="6566",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="95",STAGE="110"},
	{ID_ATTUNE="3",ID="110",TYPE="Quest",STEP="",LOCATION=Lang["Orgrimmar"],ID_WOWHEAD="6567",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="100",STAGE="120"},
	{ID_ATTUNE="3",ID="115",TYPE="Interact",STEP="",LOCATION=Lang["Desolace"],ID_WOWHEAD="10182",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="110",STAGE="130"},
	{ID_ATTUNE="3",ID="120",TYPE="Quest",STEP="",LOCATION=Lang["Desolace"],ID_WOWHEAD="6568",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="115",STAGE="140"},
	{ID_ATTUNE="3",ID="130",TYPE="Pick Up",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="6569",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="120",STAGE="150"},
	{ID_ATTUNE="3",ID="140",TYPE="Item",STEP="",LOCATION=Lang["Upper Blackrock Spire"],ID_WOWHEAD="16786",ICON="Interface\\Icons\\inv_misc_eye_01",FOLLOWS="130",STAGE="160", COUNT=20},
	{ID_ATTUNE="3",ID="145",TYPE="Turn In",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="6569",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="140",STAGE="165"},
	{ID_ATTUNE="3",ID="150",TYPE="Quest",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6570",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="145",STAGE="170"},
	{ID_ATTUNE="3",ID="160",TYPE="Pick Up",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6584",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="150",STAGE="180"},
	{ID_ATTUNE="3",ID="170",TYPE="Pick Up",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6582",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="150",STAGE="180"},
	{ID_ATTUNE="3",ID="180",TYPE="Pick Up",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6583",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="150",STAGE="180"},
	{ID_ATTUNE="3",ID="190",TYPE="Kill",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8197",ICON="Interface\\Icons\\inv_misc_head_dragon_bronze",FOLLOWS="160",STAGE="190"},
	{ID_ATTUNE="3",ID="195",TYPE="Turn In",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6584",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="190",STAGE="195"},
	{ID_ATTUNE="3",ID="200",TYPE="Kill",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="10664",ICON="Interface\\Icons\\inv_misc_head_dragon_blue",FOLLOWS="170",STAGE="190"},
	{ID_ATTUNE="3",ID="205",TYPE="Turn In",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6582",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="200",STAGE="195"},
	{ID_ATTUNE="3",ID="210",TYPE="Kill",STEP="",LOCATION=Lang["Swamp of Sorrows"],ID_WOWHEAD="12900",ICON="Interface\\Icons\\inv_misc_head_dragon_green",FOLLOWS="180",STAGE="190"},
	{ID_ATTUNE="3",ID="215",TYPE="Turn In",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6583",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="210",STAGE="195"},
	{ID_ATTUNE="3",ID="220",TYPE="Pick Up",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6585",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="195&205&215",STAGE="200"},
	{ID_ATTUNE="3",ID="230",TYPE="Kill",STEP="",LOCATION=Lang["Wetlands"],ID_WOWHEAD="12899",ICON="Interface\\Icons\\inv_misc_head_dragon_red",FOLLOWS="220",STAGE="210"},
	{ID_ATTUNE="3",ID="235",TYPE="Turn In",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6585",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="230",STAGE="215"},
	{ID_ATTUNE="3",ID="240",TYPE="Quest",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="6601",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="235",STAGE="220"},
	{ID_ATTUNE="3",ID="245",TYPE="Interact",STEP="",LOCATION=Lang["Desolace"],ID_WOWHEAD="10182",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="240",STAGE="230"},
	{ID_ATTUNE="3",ID="250",TYPE="Pick Up",STEP="",LOCATION=Lang["Desolace"],ID_WOWHEAD="6602",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="245",STAGE="240"},
	{ID_ATTUNE="3",ID="260",TYPE="Kill",STEP="",LOCATION=Lang["Upper Blackrock Spire"],ID_WOWHEAD="10363",ICON="Interface\\Icons\\inv_potion_27",FOLLOWS="250",STAGE="250"},
	{ID_ATTUNE="3",ID="265",TYPE="Interact",STEP="",LOCATION=Lang["Desolace"],ID_WOWHEAD="10182",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="260",STAGE="260"},
	{ID_ATTUNE="3",ID="268",TYPE="Turn In",STEP="",LOCATION=Lang["Desolace"],ID_WOWHEAD="6602",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="265",STAGE="265"},
	{ID_ATTUNE="3",ID="270",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_jewelry_talisman_11",FOLLOWS="268",STAGE="270"},


	{ID_ATTUNE="4",ID="10",TYPE="Level",STEP=Lang["Reach level"].." 48",LOCATION="",ID_WOWHEAD="48",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="1"},
	{ID_ATTUNE="4",ID="20",TYPE="Quest",STEP="",LOCATION=Lang["Burning Steppes"],ID_WOWHEAD="4182",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="10",STAGE="2"},
	{ID_ATTUNE="4",ID="30",TYPE="Quest",STEP="",LOCATION=Lang["Burning Steppes"],ID_WOWHEAD="4183",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="3"},
	{ID_ATTUNE="4",ID="40",TYPE="Quest",STEP="",LOCATION=Lang["Redridge Mountains"],ID_WOWHEAD="4184",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="30",STAGE="4"},
	{ID_ATTUNE="4",ID="50",TYPE="Quest",STEP="",LOCATION=Lang["Stormwind City"],ID_WOWHEAD="4185",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="40",STAGE="5"},
	{ID_ATTUNE="4",ID="60",TYPE="Quest",STEP="",LOCATION=Lang["Stormwind City"],ID_WOWHEAD="4186",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="50",STAGE="6"},
	{ID_ATTUNE="4",ID="70",TYPE="Quest",STEP="",LOCATION=Lang["Redridge Mountains"],ID_WOWHEAD="4223",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60",STAGE="7"},
	{ID_ATTUNE="4",ID="80",TYPE="Quest",STEP="",LOCATION=Lang["Burning Steppes"],ID_WOWHEAD="4224",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="70",STAGE="8"},
	{ID_ATTUNE="4",ID="90",TYPE="Quest",STEP="",LOCATION=Lang["Burning Steppes"],ID_WOWHEAD="4241",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="80",STAGE="9"},
	{ID_ATTUNE="4",ID="100",TYPE="Quest",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="4242",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="90",STAGE="10"},
	{ID_ATTUNE="4",ID="110",TYPE="Item",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="11446",ICON="Interface\\Icons\\inv_misc_note_05",FOLLOWS="100",STAGE="11"},
	{ID_ATTUNE="4",ID="120",TYPE="Quest",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="4264",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="110",STAGE="12"},
	{ID_ATTUNE="4",ID="130",TYPE="Pick Up",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="4282",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="120",STAGE="13"},
	{ID_ATTUNE="4",ID="140",TYPE="Kill",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="8983",ICON="Interface\\Icons\\inv_misc_head_dwarf_01",FOLLOWS="130",STAGE="14"},
	{ID_ATTUNE="4",ID="150",TYPE="Kill",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="9033",ICON="Interface\\Icons\\inv_misc_head_dwarf_01",FOLLOWS="130",STAGE="14"},
	{ID_ATTUNE="4",ID="160",TYPE="Item",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="11465",ICON="Interface\\Icons\\inv_misc_rune_07",FOLLOWS="140",STAGE="15"},
	{ID_ATTUNE="4",ID="170",TYPE="Item",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="11464",ICON="Interface\\Icons\\inv_misc_rune_07",FOLLOWS="150",STAGE="15"},
	{ID_ATTUNE="4",ID="175",TYPE="Turn In",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="4282",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="170&160",STAGE="16"},
	{ID_ATTUNE="4",ID="180",TYPE="Quest",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="4322",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="175",STAGE="17"},
	{ID_ATTUNE="4",ID="190",TYPE="Quest",STEP="",LOCATION=Lang["Burning Steppes"],ID_WOWHEAD="6402",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="180",STAGE="18"},
	{ID_ATTUNE="4",ID="200",TYPE="Interact",STEP="",LOCATION=Lang["Stormwind City"],ID_WOWHEAD="17804",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="190",STAGE="19"},
	{ID_ATTUNE="4",ID="210",TYPE="Quest",STEP="",LOCATION=Lang["Stormwind City"],ID_WOWHEAD="6403",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="200",STAGE="20"},
	{ID_ATTUNE="4",ID="220",TYPE="Quest",STEP="",LOCATION=Lang["Stormwind City"],ID_WOWHEAD="6501",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="210",STAGE="21"},
	{ID_ATTUNE="4",ID="230",TYPE="Interact",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="10929",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="220",STAGE="22"},
	{ID_ATTUNE="4",ID="240",TYPE="Pick Up",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="6502",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="230",STAGE="23"},
	{ID_ATTUNE="4",ID="250",TYPE="Kill",STEP="",LOCATION=Lang["Upper Blackrock Spire"],ID_WOWHEAD="10363",ICON="Interface\\Icons\\inv_potion_27",FOLLOWS="240",STAGE="24"},
	{ID_ATTUNE="4",ID="260",TYPE="Interact",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="10929",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="250",STAGE="25"},
	{ID_ATTUNE="4",ID="265",TYPE="Turn In",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="6502",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="260",STAGE="26"},	
	{ID_ATTUNE="4",ID="270",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_jewelry_talisman_11",FOLLOWS="265",STAGE="27"},

	--{ID_ATTUNE="5",ID="10",TYPE="Level",STEP=Lang["Reach level"].." 55",LOCATION="",ID_WOWHEAD="55",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="10"},
	--{ID_ATTUNE="5",ID="20",TYPE="Kill",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="9046",ICON="Interface\\Icons\\inv_misc_head_orc_01",FOLLOWS="10",STAGE="20"},
	--{ID_ATTUNE="5",ID="30",TYPE="Item",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="18987",ICON="Interface\\Icons\\inv_letter_17",FOLLOWS="20",STAGE="30"},
	--{ID_ATTUNE="5",ID="40",TYPE="Pick Up",STEP=" Command",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="7761",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="30",STAGE="40"},
	--{ID_ATTUNE="5",ID="50",TYPE="Kill",STEP="",LOCATION=Lang["Upper Blackrock Spire"],ID_WOWHEAD="10363",ICON="Interface\\Icons\\inv_misc_head_dragon_black",FOLLOWS="40",STAGE="50"},
	--{ID_ATTUNE="5",ID="60",TYPE="Click",STEP=Lang["Drakkisath's Brand"],LOCATION=Lang["Upper Blackrock Spire"],ID_WOWHEAD="1",ICON="Interface\\Icons\\inv_misc_orb_05",FOLLOWS="50",STAGE="60"},
	--{ID_ATTUNE="5",ID="65",TYPE="Turn In",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="7761",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60",STAGE="65"},
	--{ID_ATTUNE="5",ID="70",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_misc_head_dragon_black",FOLLOWS="65",STAGE="70"},

	--{ID_ATTUNE="6",ID="5",TYPE="Level",STEP=Lang["Reach level"].." 60",LOCATION="",ID_WOWHEAD="60",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="5"},
	--{ID_ATTUNE="6",ID="10",TYPE="Rep",STEP=Lang["Honored with"].." "..Lang["Argent Dawn"],LOCATION="529",ID_WOWHEAD="9000",ID_STANDING="6",ICON="Interface\\Icons\\inv_jewelry_talisman_07",FOLLOWS="5",STAGE="10"},
	--{ID_ATTUNE="6",ID="20",TYPE="Rep",STEP=Lang["Revered with"].." "..Lang["Argent Dawn"],LOCATION="529",ID_WOWHEAD="21000",ID_STANDING="7",ICON="Interface\\Icons\\inv_jewelry_talisman_07",FOLLOWS="5",STAGE="10"},
	--{ID_ATTUNE="6",ID="30",TYPE="Rep",STEP=Lang["Exalted with"].." "..Lang["Argent Dawn"],LOCATION="529",ID_WOWHEAD="42000",ID_STANDING="8",ICON="Interface\\Icons\\inv_jewelry_talisman_07",FOLLOWS="5",STAGE="10"},
	--{ID_ATTUNE="6",ID="40",TYPE="Quest",STEP="",LOCATION=Lang["Eastern Plaguelands"],ID_WOWHEAD="9121",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="10",STAGE="20"},
	--{ID_ATTUNE="6",ID="50",TYPE="Quest",STEP="",LOCATION=Lang["Eastern Plaguelands"],ID_WOWHEAD="9122",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="20"},
	--{ID_ATTUNE="6",ID="60",TYPE="Quest",STEP="",LOCATION=Lang["Eastern Plaguelands"],ID_WOWHEAD="9123",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="30",STAGE="20"},
	--{ID_ATTUNE="6",ID="90",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_trinket_naxxramas06",FOLLOWS="40|50|60",STAGE="30"},

	--{ID_ATTUNE="10",ID="10",TYPE="Interact",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="15180",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="0",STAGE="10"},
	--{ID_ATTUNE="10",ID="20",TYPE="Quest",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="8286",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="10",STAGE="20"},
	--{ID_ATTUNE="10",ID="30",TYPE="Pick Up",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="8288",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="30"},
	--{ID_ATTUNE="10",ID="40",TYPE="Kill",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="12017",ICON="Interface\\Icons\\inv_misc_head_dragon_black",FOLLOWS="30",STAGE="40"},
	--{ID_ATTUNE="10",ID="50",TYPE="Item",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="20383",ICON="Interface\\Icons\\spell_shadow_curseoftounges",FOLLOWS="40",STAGE="50"},
	--{ID_ATTUNE="10",ID="60",TYPE="Turn In",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="8288",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="50",STAGE="60"},
	--{ID_ATTUNE="10",ID="65",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="70"},
	--{ID_ATTUNE="10",ID="70",TYPE="Quest",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="8301",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60",STAGE="70"},
	--{ID_ATTUNE="10",ID="80",TYPE="Rep",STEP=Lang["Neutral with"].." "..Lang["Brood of Nozdormu"],LOCATION="910",ID_WOWHEAD="0",ID_STANDING="4",ICON="Interface\\Icons\\inv_misc_head_dragon_bronze",FOLLOWS="0",STAGE="70", OFFSET=42000},
	--{ID_ATTUNE="10",ID="100",TYPE="Quest",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="8303",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="80&70",STAGE="80"},
	--{ID_ATTUNE="10",ID="110",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8305",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="100",STAGE="90"},
	--{ID_ATTUNE="10",ID="120",TYPE="Click",STEP=Lang["Crystalline Tear"],LOCATION=Lang["Silithus"],ID_WOWHEAD="2",ICON="Interface\\Icons\\inv_misc_gem_ruby_01",FOLLOWS="110",STAGE="100"},
	--{ID_ATTUNE="10",ID="130",TYPE="Quest",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="8519",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="120",STAGE="110"},
	--{ID_ATTUNE="10",ID="140",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8555",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="130",STAGE="120"},
	--{ID_ATTUNE="10",ID="150",TYPE="Interact",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="13020",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="140",STAGE="130"},
	--{ID_ATTUNE="10",ID="160",TYPE="Pick Up",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="8730",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="150",STAGE="140"},
	--{ID_ATTUNE="10",ID="170",TYPE="Kill",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="11583",ICON="Interface\\Icons\\inv_misc_head_dragon_black",FOLLOWS="160",STAGE="150"},
	--{ID_ATTUNE="10",ID="180",TYPE="Item",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="21138",ICON="Interface\\Icons\\inv_misc_gem_ruby_03",FOLLOWS="170",STAGE="160"},
	--{ID_ATTUNE="10",ID="190",TYPE="Turn In",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="8730",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="180",STAGE="170"},
	--{ID_ATTUNE="10",ID="200",TYPE="Interact",STEP="",LOCATION=Lang["The Temple of Atal'Hakkar"],ID_WOWHEAD="15362",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="140",STAGE="130"},
	--{ID_ATTUNE="10",ID="210",TYPE="Quest",STEP="",LOCATION=Lang["The Temple of Atal'Hakkar"],ID_WOWHEAD="8733",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="200",STAGE="140"},
	--{ID_ATTUNE="10",ID="220",TYPE="Interact",STEP="",LOCATION=Lang["Teldrassil"],ID_WOWHEAD="15624",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="210",STAGE="150"},
	--{ID_ATTUNE="10",ID="230",TYPE="Quest",STEP="",LOCATION=Lang["Teldrassil"],ID_WOWHEAD="8734",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="220",STAGE="160"},
	--{ID_ATTUNE="10",ID="241",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="160"},
	--{ID_ATTUNE="10",ID="242",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="160"},
	--{ID_ATTUNE="10",ID="240",TYPE="Pick Up",STEP="",LOCATION=Lang["Moonglade"],ID_WOWHEAD="8735",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="230",STAGE="170"},
	--{ID_ATTUNE="10",ID="241",TYPE="Item",STEP="",LOCATION=Lang["Hinterlands"],ID_WOWHEAD="21146",ICON="Interface\\Icons\\spell_shadow_antimagicshell",FOLLOWS="0",STAGE="170"},
	--{ID_ATTUNE="10",ID="242",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="170"},
	--{ID_ATTUNE="10",ID="250",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="180"},
	--{ID_ATTUNE="10",ID="251",TYPE="Item",STEP="",LOCATION=Lang["Ashenvale"],ID_WOWHEAD="21147",ICON="Interface\\Icons\\spell_shadow_antimagicshell",FOLLOWS="0",STAGE="180"},
	--{ID_ATTUNE="10",ID="252",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="182"},
	--{ID_ATTUNE="10",ID="253",TYPE="Item",STEP="",LOCATION=Lang["Feralas"],ID_WOWHEAD="21148",ICON="Interface\\Icons\\spell_shadow_antimagicshell",FOLLOWS="0",STAGE="182"},
	--{ID_ATTUNE="10",ID="254",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="184"},
	--{ID_ATTUNE="10",ID="255",TYPE="Item",STEP="",LOCATION=Lang["Duskwood"],ID_WOWHEAD="21149",ICON="Interface\\Icons\\spell_shadow_antimagicshell",FOLLOWS="0",STAGE="184"},
	--{ID_ATTUNE="10",ID="259",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="190"},
	--{ID_ATTUNE="10",ID="260",TYPE="Turn In",STEP="",LOCATION=Lang["Moonglade"],ID_WOWHEAD="8735",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="240&241&251&253&255",STAGE="190"},
	--{ID_ATTUNE="10",ID="261",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="190"},
	--{ID_ATTUNE="10",ID="262",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="190"},
	--{ID_ATTUNE="10",ID="269",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="200"},
	--{ID_ATTUNE="10",ID="270",TYPE="Quest",STEP="",LOCATION=Lang["Moonglade"],ID_WOWHEAD="8736",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="260",STAGE="200"},
	--{ID_ATTUNE="10",ID="271",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="200"},
	--{ID_ATTUNE="10",ID="272",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="200"},
	--{ID_ATTUNE="10",ID="279",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="210"},
	--{ID_ATTUNE="10",ID="280",TYPE="Item",STEP="",LOCATION=Lang["Moonglade"],ID_WOWHEAD="21139",ICON="Interface\\Icons\\inv_misc_gem_emerald_03",FOLLOWS="270",STAGE="210"},
	--{ID_ATTUNE="10",ID="281",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="210"},
	--{ID_ATTUNE="10",ID="282",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="210"},
	--{ID_ATTUNE="10",ID="289",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="220"},
	--{ID_ATTUNE="10",ID="290",TYPE="Quest",STEP="",LOCATION=Lang["Moonglade"],ID_WOWHEAD="8741",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="280",STAGE="220"},
	--{ID_ATTUNE="10",ID="291",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="220"},
	--{ID_ATTUNE="10",ID="292",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="220"},
	--{ID_ATTUNE="10",ID="299",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="130"},
	--{ID_ATTUNE="10",ID="300",TYPE="Interact",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="15481",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="140",STAGE="130"},
	--{ID_ATTUNE="10",ID="309",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="140"},
	--{ID_ATTUNE="10",ID="310",TYPE="Pick Up",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="8575",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="300",STAGE="140"},
	--{ID_ATTUNE="10",ID="319",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="150"},
	--{ID_ATTUNE="10",ID="320",TYPE="Interact",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="11811",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="310",STAGE="150"},
	--{ID_ATTUNE="10",ID="327",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="222"},
	--{ID_ATTUNE="10",ID="328",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="222"},
	--{ID_ATTUNE="10",ID="329",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="222"},
	--{ID_ATTUNE="10",ID="330",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8576",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="320",STAGE="222"},
	--{ID_ATTUNE="10",ID="339",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="225"},
	--{ID_ATTUNE="10",ID="349",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="230"},
	--{ID_ATTUNE="10",ID="358",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="240"},
	--{ID_ATTUNE="10",ID="368",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="250"},
	--{ID_ATTUNE="10",ID="531",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="276"},
	--{ID_ATTUNE="10",ID="549",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="280"},
	--{ID_ATTUNE="10",ID="551",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="281"},
	--{ID_ATTUNE="10",ID="553",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="283"},
	--{ID_ATTUNE="10",ID="555",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="284"},
	--{ID_ATTUNE="10",ID="557",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="285"},
	--{ID_ATTUNE="10",ID="559",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="286"},
	--{ID_ATTUNE="10",ID="561",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="287"},
	--{ID_ATTUNE="10",ID="563",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="288"},
	--{ID_ATTUNE="10",ID="565",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="289"},
	--{ID_ATTUNE="10",ID="567",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="290"},
	--{ID_ATTUNE="10",ID="450",TYPE="Pick Up",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8597",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="330",STAGE="225"},
	--{ID_ATTUNE="10",ID="460",TYPE="Interact",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="15526",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="450",STAGE="230"},
	--{ID_ATTUNE="10",ID="470",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8599",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="460",STAGE="240"},
	--{ID_ATTUNE="10",ID="480",TYPE="Interact",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="15526",ICON="Interface\\Icons\\spell_nature_wispsplode",FOLLOWS="470",STAGE="250"},
	--{ID_ATTUNE="10",ID="490",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8597",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="480",STAGE="260"},
	--{ID_ATTUNE="10",ID="500",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8598",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="490",STAGE="270"},
	--{ID_ATTUNE="10",ID="510",TYPE="Pick Up",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8606",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="500",STAGE="272"},
	--{ID_ATTUNE="10",ID="520",TYPE="Kill",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="15554",ICON="Interface\\Icons\\ability_hunter_pet_gorilla",FOLLOWS="510",STAGE="274"},
	--{ID_ATTUNE="10",ID="530",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8606",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="520",STAGE="276"},
	--{ID_ATTUNE="10",ID="540",TYPE="Pick Up",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8620",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="530",STAGE="278"},
	--{ID_ATTUNE="10",ID="546",TYPE="Kill",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="15552",ICON="Interface\\AddOns\\Attune\\Images\\achievement_character_gnome_male",FOLLOWS="0",STAGE="278"},
	--{ID_ATTUNE="10",ID="550",TYPE="Item",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="21103",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="546",STAGE="280"},
	--{ID_ATTUNE="10",ID="552",TYPE="Item",STEP="",LOCATION=Lang["Blasted Lands"],ID_WOWHEAD="21104",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="0",STAGE="281"},
	--{ID_ATTUNE="10",ID="554",TYPE="Item",STEP="",LOCATION=Lang["Winterspring"],ID_WOWHEAD="21105",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="0",STAGE="283"},
	--{ID_ATTUNE="10",ID="556",TYPE="Item",STEP="",LOCATION=Lang["Undercity"],ID_WOWHEAD="21106",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="0",STAGE="284"},
	--{ID_ATTUNE="10",ID="558",TYPE="Item",STEP="",LOCATION=Lang["Stormwind"],ID_WOWHEAD="21107",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="0",STAGE="285"},
	--{ID_ATTUNE="10",ID="560",TYPE="Kill",STEP="",LOCATION=Lang["Onyxia's Lair"],ID_WOWHEAD="10184",ICON="Interface\\Icons\\inv_misc_head_dragon_01",FOLLOWS="0",STAGE="286"},
	--{ID_ATTUNE="10",ID="562",TYPE="Item",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="21108",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="560",STAGE="287"},
	--{ID_ATTUNE="10",ID="564",TYPE="Item",STEP="",LOCATION=Lang["Blackwing Lair"],ID_WOWHEAD="21109",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="0",STAGE="288"},
	--{ID_ATTUNE="10",ID="566",TYPE="Kill",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="11502",ICON="Interface\\Icons\\inv_hammer_unique_sulfuras",FOLLOWS="0",STAGE="289"},
	--{ID_ATTUNE="10",ID="568",TYPE="Item",STEP="",LOCATION=Lang["Dustwallow Marsh"],ID_WOWHEAD="21110",ICON="Interface\\Icons\\inv_misc_stonetablet_03",FOLLOWS="566",STAGE="290"},
	--{ID_ATTUNE="10",ID="570",TYPE="Item",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="21111",ICON="Interface\\Icons\\inv_misc_book_06",FOLLOWS="540&550&552&554&556&558&562&564&568",STAGE="295"},
	--{ID_ATTUNE="10",ID="580",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8620",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="570",STAGE="300"},
	--{ID_ATTUNE="10",ID="571",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="295"},
	--{ID_ATTUNE="10",ID="581",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="300"},
	--{ID_ATTUNE="10",ID="680",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8584",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="330",STAGE="225"},
	--{ID_ATTUNE="10",ID="690",TYPE="Pick Up",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8585",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="680",STAGE="230"},
	--{ID_ATTUNE="10",ID="695",TYPE="Kill",STEP="",LOCATION=Lang["Feralas"],ID_WOWHEAD="12803",ICON="Interface\\AddOns\\Attune\\Images\\ability_hunter_pet_chimera",FOLLOWS="690",STAGE="240"},
	--{ID_ATTUNE="10",ID="700",TYPE="Item",STEP="",LOCATION=Lang["Feralas"],ID_WOWHEAD="21027",ICON="Interface\\Icons\\inv_misc_food_15",FOLLOWS="695",STAGE="250"},
	--{ID_ATTUNE="10",ID="710",TYPE="Item",STEP="",LOCATION=Lang["Feralas"],ID_WOWHEAD="21024",ICON="Interface\\Icons\\inv_misc_food_70",FOLLOWS="700",STAGE="260", COUNT=20},
	--{ID_ATTUNE="10",ID="720",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8585",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="710",STAGE="270"},
	--{ID_ATTUNE="10",ID="730",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8586",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="720",STAGE="272"},
	--{ID_ATTUNE="10",ID="740",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8587",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="730",STAGE="274"},
	--{ID_ATTUNE="10",ID="790",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8577",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="330",STAGE="225"},
	--{ID_ATTUNE="10",ID="800",TYPE="Pick Up",STEP="",LOCATION=Lang["Silverpine Forest"],ID_WOWHEAD="8578",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="790",STAGE="230"},
	--{ID_ATTUNE="10",ID="810",TYPE="Item",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="20951",ICON="Interface\\Icons\\inv_helmet_47",FOLLOWS="800",STAGE="240"},
	--{ID_ATTUNE="10",ID="820",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8578",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="810",STAGE="250"},
	--{ID_ATTUNE="10",ID="887",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="310"},
	--{ID_ATTUNE="10",ID="888",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="310"},
	--{ID_ATTUNE="10",ID="889",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="310"},	
	--{ID_ATTUNE="10",ID="890",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8728",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="580&820&740",STAGE="310"},
	--{ID_ATTUNE="10",ID="900",TYPE="Pick Up",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8729",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="890",STAGE="320"},
	--{ID_ATTUNE="10",ID="910",TYPE="Kill",STEP="Maws",LOCATION=Lang["Azshara"],ID_WOWHEAD="15571",ICON="Interface\\AddOns\\Attune\\Images\\inv_pet_babyshark",FOLLOWS="900",STAGE="330"},
	--{ID_ATTUNE="10",ID="920",TYPE="Item",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="21137",ICON="Interface\\Icons\\inv_misc_gem_sapphire_03",FOLLOWS="910",STAGE="340"},
	--{ID_ATTUNE="10",ID="930",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8729",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="920",STAGE="350"},
	--{ID_ATTUNE="10",ID="940",TYPE="Quest",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="8742",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="190&290&930",STAGE="360"},
	--{ID_ATTUNE="10",ID="941",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="360"},
	--{ID_ATTUNE="10",ID="942",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="360"},
	--{ID_ATTUNE="10",ID="943",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="",ICON="",FOLLOWS="0",STAGE="360"},
	----{ID_ATTUNE="10",ID="950",TYPE="Item",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="21175",ICON="Interface\\Icons\\inv_hammer_25",FOLLOWS="940",STAGE="370"},
	--{ID_ATTUNE="10",ID="960",TYPE="Quest",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="8745",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="940",STAGE="380"},
	--{ID_ATTUNE="10",ID="970",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="",ICON="Interface\\Icons\\inv_hammer_25",FOLLOWS="960",STAGE="390"},
	{ID_ATTUNE="12",ID="10",TYPE="Level",STEP=Lang["Reach level"].." 48",LOCATION="",ID_WOWHEAD="48",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="10"},
	{ID_ATTUNE="12",ID="20",TYPE="Interact",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="8888",ICON="Interface\\Icons\\achievement_character_dwarf_male",FOLLOWS="10",STAGE="20"},
	{ID_ATTUNE="12",ID="30",TYPE="Quest",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="3801",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="30"},
	{ID_ATTUNE="12",ID="40",TYPE="Pick Up",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="3802",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="30",STAGE="40"},
	{ID_ATTUNE="12",ID="50",TYPE="Kill",STEP="",LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="9056",ICON="Interface\\Icons\\Inv_misc_head_dwarf_01",FOLLOWS="40",STAGE="50"},
	{ID_ATTUNE="12",ID="60",TYPE="Click",STEP=Lang["Shrine of Thaurissan"],LOCATION=Lang["Blackrock Depths"],ID_WOWHEAD="3",ICON="Interface\\Icons\\inv_hammer_23",FOLLOWS="50",STAGE="60"},
	{ID_ATTUNE="12",ID="65",TYPE="Turn In",STEP="",LOCATION=Lang["Blackrock Mountain"],ID_WOWHEAD="3802",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60",STAGE="65"},
	{ID_ATTUNE="12",ID="70",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_misc_key_08",FOLLOWS="65",STAGE="70"},


	{ID_ATTUNE="14",ID="4",TYPE="Level",STEP=Lang["Reach level"].." 50",LOCATION="",ID_WOWHEAD="50",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="4"},
	{ID_ATTUNE="14",ID="6",TYPE="Quest",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5096",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="4",STAGE="6"},
	{ID_ATTUNE="14",ID="7",TYPE="Quest",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5098",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="6",STAGE="7"},
	{ID_ATTUNE="14",ID="10",TYPE="Level",STEP=Lang["Reach level"].." 55",LOCATION="",ID_WOWHEAD="55",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="7",STAGE="10"},
	{ID_ATTUNE="14",ID="20",TYPE="Interact",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="10837",ICON="Interface\\Icons\\inv_misc_head_undead_01",FOLLOWS="10",STAGE="20"},
	{ID_ATTUNE="14",ID="30",TYPE="Quest",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="838",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="30"},
	{ID_ATTUNE="14",ID="40",TYPE="Quest",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="964",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="30",STAGE="40"},
	{ID_ATTUNE="14",ID="50",TYPE="Pick Up",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5514",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="40",STAGE="50"},
	{ID_ATTUNE="14",ID="60",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="5514",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="50",STAGE="60"},
	{ID_ATTUNE="14",ID="70",TYPE="Pick Up",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="5802",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60",STAGE="70"},
	{ID_ATTUNE="14",ID="80",TYPE="Turn In",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5802",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="70",STAGE="80"},
	{ID_ATTUNE="14",ID="90",TYPE="Pick Up",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5804",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="80",STAGE="90"},
	{ID_ATTUNE="14",ID="100",TYPE="Kill",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="1852",ICON="Interface\\Icons\\spell_frost_frostarmor",FOLLOWS="90",STAGE="100"},
	{ID_ATTUNE="14",ID="110",TYPE="Item",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="14610",ICON="Interface\\Icons\\spell_shadow_grimward",FOLLOWS="100",STAGE="110"},
	{ID_ATTUNE="14",ID="120",TYPE="Turn In",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5804",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="110",STAGE="120"},
	{ID_ATTUNE="14",ID="130",TYPE="Quest",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5511",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="120",STAGE="130"},
	{ID_ATTUNE="14",ID="140",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_misc_key_11",FOLLOWS="130",STAGE="140"},
	
	{ID_ATTUNE="15",ID="4",TYPE="Level",STEP=Lang["Reach level"].." 50",LOCATION="",ID_WOWHEAD="50",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="4"},
	{ID_ATTUNE="15",ID="6",TYPE="Quest",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5092",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="4",STAGE="6"},
	{ID_ATTUNE="15",ID="7",TYPE="Quest",STEP="",LOCATION=Lang["Tirisfal Glades"],ID_WOWHEAD="5097",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="6",STAGE="7"},
	{ID_ATTUNE="15",ID="10",TYPE="Level",STEP=Lang["Reach level"].." 55",LOCATION="",ID_WOWHEAD="55",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="7",STAGE="10"},
	{ID_ATTUNE="15",ID="20",TYPE="Interact",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="10838",ICON="Interface\\Icons\\inv_bannerpvp_02",FOLLOWS="10",STAGE="20"},
	{ID_ATTUNE="15",ID="30",TYPE="Quest",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="5533",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="30"},
	{ID_ATTUNE="15",ID="40",TYPE="Quest",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="5537",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="30",STAGE="40"},
	{ID_ATTUNE="15",ID="50",TYPE="Pick Up",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="5538",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="40",STAGE="50"},
	{ID_ATTUNE="15",ID="60",TYPE="Turn In",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="5538",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="50",STAGE="60"},
	{ID_ATTUNE="15",ID="70",TYPE="Pick Up",STEP="",LOCATION=Lang["Tanaris"],ID_WOWHEAD="5801",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60",STAGE="70"},
	{ID_ATTUNE="15",ID="80",TYPE="Turn In",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="5801",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="70",STAGE="80"},
	{ID_ATTUNE="15",ID="90",TYPE="Pick Up",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="5803",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="80",STAGE="90"},
	{ID_ATTUNE="15",ID="100",TYPE="Kill",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="1852",ICON="Interface\\Icons\\spell_frost_frostarmor",FOLLOWS="90",STAGE="100"},
	{ID_ATTUNE="15",ID="110",TYPE="Item",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="14610",ICON="Interface\\Icons\\spell_shadow_grimward",FOLLOWS="100",STAGE="110"},
	{ID_ATTUNE="15",ID="120",TYPE="Turn In",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="5803",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="110",STAGE="120"},
	{ID_ATTUNE="15",ID="130",TYPE="Quest",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="5505",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="120",STAGE="130"},
	{ID_ATTUNE="15",ID="140",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_misc_key_11",FOLLOWS="130",STAGE="140"},

	{ID_ATTUNE="8",ID="10",TYPE="Level",STEP=Lang["Reach level"].." 55",LOCATION="",ID_WOWHEAD="55",ICON="Interface\\Icons\\spell_holy_innerfire",FOLLOWS="0",STAGE="10"},
	{ID_ATTUNE="8",ID="20",TYPE="Interact",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="13278",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="10",STAGE="20"},
	{ID_ATTUNE="8",ID="30",TYPE="Quest",STEP="",LOCATION=Lang["Western Plaguelands"],ID_WOWHEAD="6804",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="30"},
	{ID_ATTUNE="8",ID="40",TYPE="Quest",STEP="",LOCATION=Lang["Silithus"],ID_WOWHEAD="6805",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="20",STAGE="30"},
	{ID_ATTUNE="8",ID="50",TYPE="Quest",STEP="",LOCATION=Lang["Upper Blackrock Spire"],ID_WOWHEAD="6821",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="30&40",STAGE="40"},
	{ID_ATTUNE="8",ID="60",TYPE="Quest",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="6822",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="50",STAGE="50"},
	{ID_ATTUNE="8",ID="68",TYPE="Spacer",STEP="Spacer",LOCATION="",ID_WOWHEAD="0",ICON="",FOLLOWS="0",STAGE="60"},
	{ID_ATTUNE="8",ID="70",TYPE="Pick Up",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="6823",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="60",STAGE="60"},
	{ID_ATTUNE="8",ID="80",TYPE="Rep",STEP=Lang["Honored with"].." "..Lang["Hydraxian Waterlords"],LOCATION="749",ID_WOWHEAD="9000",ID_STANDING="6",ICON="Interface\\Icons\\spell_frost_summonwaterelemental",FOLLOWS="0",STAGE="60"},
	{ID_ATTUNE="8",ID="90",TYPE="Turn In",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="6823",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="70&80",STAGE="80"},
	{ID_ATTUNE="8",ID="100",TYPE="Pick Up",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="6824",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="90",STAGE="90"},
	{ID_ATTUNE="8",ID="110",TYPE="Kill",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="12264",ICON="Interface\\AddOns\\Attune\\Images\\flamewalker-blue",FOLLOWS="100",STAGE="100"},
	{ID_ATTUNE="8",ID="120",TYPE="Kill",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="12118",ICON="Interface\\AddOns\\Attune\\Images\\flamewalker-gray",FOLLOWS="100",STAGE="100"},
	{ID_ATTUNE="8",ID="130",TYPE="Kill",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="12259",ICON="Interface\\AddOns\\Attune\\Images\\flamewalker-red",FOLLOWS="100",STAGE="100"},
	{ID_ATTUNE="8",ID="140",TYPE="Kill",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="12098",ICON="Interface\\AddOns\\Attune\\Images\\flamewalker-red",FOLLOWS="100",STAGE="100"},
	{ID_ATTUNE="8",ID="150",TYPE="Item",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="17332",ICON="Interface\\Icons\\inv_gauntlets_19",FOLLOWS="110",STAGE="110"},
	{ID_ATTUNE="8",ID="160",TYPE="Item",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="17329",ICON="Interface\\Icons\\inv_gauntlets_26",FOLLOWS="120",STAGE="110"},
	{ID_ATTUNE="8",ID="170",TYPE="Item",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="17331",ICON="Interface\\Icons\\spell_fire_immolation",FOLLOWS="130",STAGE="110"},
	{ID_ATTUNE="8",ID="180",TYPE="Item",STEP="",LOCATION=Lang["Molten Core"],ID_WOWHEAD="17330",ICON="Interface\\Icons\\inv_gauntlets_03",FOLLOWS="140",STAGE="110"},
	{ID_ATTUNE="8",ID="190",TYPE="Turn In",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="6824",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="150&160&170&180",STAGE="120"},
	{ID_ATTUNE="8",ID="200",TYPE="Quest",STEP="",LOCATION=Lang["Azshara"],ID_WOWHEAD="7486",ICON="Interface\\Icons\\inv_scroll_03",FOLLOWS="190",STAGE="130"},
	{ID_ATTUNE="8",ID="210",TYPE="End",STEP="Attuned",LOCATION="",ID_WOWHEAD="0",ICON="Interface\\Icons\\inv_potion_76",FOLLOWS="200",STAGE="140"},
-- [id] = title, minlevel, groupsize, desc

Attune_Data.quests = {
	[7848]={55,5}				[7847]={46,1}				[4903]={55,5}				[4941]={55,1}				[4974]={55,10}				[6566]={55,1}				[6567]={55,1}
	[6568]={55,1}				[6569]={55,10}				[6570]={55,1}				[6582]={55,5}				[6583]={55,5}				[6584]={55,5}				[6585]={55,5}
	[6601]={55,1}				[6602]={55,10}				[4182]={48,2}				[4183]={48,1}				[4184]={48,1}				[4185]={48,1}				[4186]={48,1}
	[4223]={48,1}				[4224]={48,1}				[4241]={48,5}				[4242]={48,1}				[4264]={50,1}				[4282]={50,5}				[4322]={50,5}
	[6402]={50,1}				[6403]={50,1}				[6501]={50,1}				[6502]={50,10}				[7761]={55,10}				[9122]={60,1}				[9121]={60,1}
	[9123]={60,1}				[8286]={60,1}				[8288]={60,40}				[8301]={60,2}				[8303]={60,1}				[8305]={60,1}				[8519]={60,1}
	[8555]={60,1}				[8575]={60,1}				[8576]={60,1}				[8577]={60,1}				[8578]={60,40}				[8728]={60,1}				[8729]={60,25}
	[8742]={60,1}				[8745]={60,1}				[8584]={60,1}				[8585]={60,8}				[8586]={60,1}				[8587]={60,1}				[8597]={60,1}
	[8599]={60,1}				[8598]={60,1}				[8606]={60,1}				[8620]={60,40}				[8733]={60,5}				[8734]={60,1}				[8735]={60,40}
	[8736]={60,40}				[8741]={60,1}				[8730]={60,40}
	[3801]={48,1}
	[838]={55,1}				[964]={55,1}				[5514]={55,1}				[5537]={55,1}				[5802]={55,1}				[5804]={55,3}
	[5511]={55,1}				[5803]={55,3}				[5533]={55,1}				[5538]={55,1}				[5801]={55,1}				[5097]={50,1}				[5098]={50,1}
	[5505]={50,1}				[5096]={50,1}				[5092]={50,1}				[6804]={55,1}				[6805]={55,1}				[6821]={55,10}				[6822]={55,40}
	[6823]={55,40}				[6824]={55,40}				[7486]={55,1}
	[26303] = {55, 1}
	[26304] = {55, 1}
	[26305] = {55, 5}
	[26306] = {55, 5}
	[26307] = {55, 1}
}

Attune_Data.npcs = {
	[3296] = { "55", "", "Org Grunt"},
	[6466] = { "12", "", "Gamon"},
	[3100] = { "8", "",  "Elder Mottled Boar"},	
	[9568] = { "60", Lang["Elite"], Lang["Dragonkin"]},
	[9237] = { "59", Lang["Elite"], Lang["Troll"]},
	[9196] = { "59", Lang["Elite"], Lang["Ogre"]},
	[10429] = { "??", Lang["Boss"], Lang["Orc"]},
	[8197] = { "61", Lang["Elite"], Lang["Dragonkin"]},
	[10664] = { "60", Lang["Elite"], Lang["Dragonkin"]},
	[12900] = { "62", Lang["Elite"], Lang["Dragonkin"]},
	[12899] = { "62", Lang["Elite"], Lang["Dragonkin"]},
	[10182] = { "??", Lang["Elite"], Lang["Half-Orc"]},
	[10929]	= { "62", Lang["Elite"], Lang["Dragonkin (in Blood Elf form)"]},
	[17804]	= { "52", "", Lang["Human"]},
	[10363]	= { "??", Lang["Boss"], Lang["Dragonkin"]},
	[8983]	= { "57", Lang["Elite"], Lang["Dwarf"]},
	[9033]	= { "57", Lang["Elite"], Lang["Dwarf"]},
	[9046]	= { "55", Lang["Rare Elite"], Lang["Orc"]},
	[22037]	= { "69", "", Lang["Orc"]},
	[18733] = { "70", Lang["Elite"], Lang["Mechanical"]},
	[18473] = { "69", Lang["Elite"], Lang["Arakkoa"]},	
	[18472] = { "69", Lang["Elite"], Lang["Arakkoa"]},	
	[20142] = { "70", Lang["Elite"], Lang["Dragonkin"]},	
	[18096] = { "68", Lang["Elite"], Lang["Dragonkin"]},	
	[20130] = { "70", Lang["Elite"], Lang["Dragonkin (in Humanoid form)"]},
	[19880] = { "70", "", Lang["Ethereal"]},	
	[19641] = { "70", "", Lang["Ethereal"]},	
	[19220] = { "72", Lang["Elite"], Lang["Blood Elf"]},	
	[17977] = { "72", Lang["Elite"], Lang["Elemental"]},	
	[18481] = { "73", Lang["Elite"], Lang["Shiny thingy"]},	
	[17613] = { "70", "", Lang["Human"]},	
	[18708] = { "72", Lang["Elite"], Lang["Elemental"]},	
	[17797] = { "72", Lang["Elite"], Lang["Naga"]},
	[20870] = { "72", Lang["Elite"], Lang["Demon"]},	
	[15608] = { "??", Lang["Boss"], Lang["Human"]},	
	[22421] = { "70", Lang["Elite"], Lang["Naga"]},	
	[19044] = { "??", Lang["Boss"], Lang["Gronn"]},
	[17225] = { "??", Lang["Boss"], Lang["Undead (in Dragon form)"]},	
	[21938] = { "68", "", Lang["Tauren"]},	
	[21183] = { "70", "", Lang["Orc"]},	
	[21291] = { "70", "", Lang["Orc"]},	
	[21292] = { "70", "", Lang["Orc"]},	
	[21293] = { "70", "", Lang["Orc"]},	
	[18166] = { "??", Lang["Boss"], Lang["Human"]},	
	[16808] = { "72", Lang["Elite"], Lang["Orc"]},	
	[16807] = { "72", Lang["Elite"], Lang["Orc"]},	
	[17798] = { "72", Lang["Elite"], Lang["Naga"]},	
	[20912] = { "72", Lang["Elite"], Lang["Qiraji"]},	
	[20977] = { "70", Lang["Elite"], Lang["Gnome"]},	
	[21937] = { "65", "", Lang["Broken"]},	
	[17257] = { "??", Lang["Boss"], Lang["Demon"]},	
	[19935] = { "70", Lang["Elite"], Lang["Dragonkin (in Blood Elf form)"]},	
	[19622] = { "??", Lang["Boss"], Lang["Blood Elf"]},	
	[21212] = { "??", Lang["Boss"], Lang["Naga"]},	
	[21402] = { "70", "", Lang["Draenei"]},	
	[21955] = { "70", Lang["Elite"], Lang["Blood Elf"]},	
	[21962] = { "70", "", Lang["Broken"]},	
	[22006] = { "70", Lang["Elite"], Lang["Orc"]},	
	[22820] = { "70", "", Lang["Broken"]},	
	[21700] = { "70", Lang["Elite"], Lang["Broken"]},	
	[19514] = { "??", Lang["Boss"], Lang["Elemental"]},	
	[17767] = { "??", Lang["Boss"], Lang["Undead"]},	
	[18528] = { "70", Lang["Elite"], Lang["Shiny thingy"]},	
	[15552] = { "63", Lang["Elite"], Lang["Gnome"]},
	[15554] = { "61", Lang["Elite"], Lang["Gorilla"]},	
	[15571] = { "??", Lang["Boss"], Lang["Shark"]},	
	[12803] = { "62", Lang["Elite"], Lang["Chimaera"]},	
	[11583] = { "??", Lang["Boss"], Lang["Dragonkin"]},	
	[13020] = { "??", Lang["Boss"], Lang["Dragonkin"]},	
	[12017] = { "??", Lang["Boss"], Lang["Dragonkin"]},	
	[15624] = { "8", "", Lang["Wisp"]},	
	[15180] = { "60", "", Lang["Night-Elf"]},	
	[15526] = { "60", "", Lang["Naga"]},	
	[11811] = { "45", "", Lang["Gnome"]},	
	[15362] = { "??", Lang["Boss"], Lang["Night-Elf"]},	
	[15481] = { "??", Lang["Boss"], Lang["Dragonkin"]},	
	[11502] = { "??", Lang["Boss"], Lang["Elemental"]},	
	[10184] = { "??", Lang["Boss"], Lang["Dragonkin"]},	
	[16524] = { "??", Lang["Boss"], Lang["Undead"]},
	[22497] = { "72", Lang["Elite"], Lang["Shiny thingy"]},	
	[22941] = { "68", "", Lang["Ogre"]},
	[22113] = { "71", Lang["Elite"], Lang["Dragonkin (in Blood Elf form)"]},		
	[8888]  = { "60", Lang["Elite"], Lang["Dwarf"]}, 
	[9056]  = { "54", Lang["Elite"], Lang["Dwarf"]},
	[10837] = { "61", "", Lang["Undead"] },
	[10838] = { "61", "", Lang["Human"] },
	[1852]  = { "61", Lang["Elite"], Lang["Undead"] },
	[13278] = { "60", Lang["Elite"], Lang["Elemental"]},	
	[12264] = { "??", Lang["Boss"], Lang["Flamewaker"]},	
	[12118] = { "??", Lang["Boss"], Lang["Flamewaker"]},	
	[12259] = { "??", Lang["Boss"], Lang["Flamewaker"]},	
	[12098] = { "??", Lang["Boss"], Lang["Flamewaker"]},	
}

Attune_Data.factionIDMap = {
	--vanilla
	[529] = Lang["Argent Dawn"],
	[749] = Lang["Hydraxian Waterlords"],
	[910] = Lang["Brood of Nozdormu"],
}